#!/usr/bin/env python3
# 
# (C) 2025 Inria, Universite Grenoble Alpes
# For the license applied to these sources refer to file ../doc/LICENSE.txt
# 
# This file allows to plot CSV files generated by the noxim_explorer tool
#
# Author: Cesar Fuguet <cesar.fuguet@univ-grenoble-alpes.fr>
# Date: February 17, 2025
#
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import argparse
import os

mpl.rcParams['axes.titleweight'] = 'bold'
mpl.rcParams['axes.titlesize'] = 'Large'
mpl.rcParams['axes.labelsize'] = 'Large'
mpl.rcParams.update({'legend.fontsize': 23})
mpl.rcParams.update({'font.size': 28})
mpl.rcParams.update({'lines.linewidth': 5})
mpl.rcParams.update({'lines.markersize': 10})

parser = argparse.ArgumentParser('Plot network explorer performance')
parser.add_argument('csv_files', nargs='+', type=str)
parser.add_argument('--names', '-n', nargs='+', type=str)
parser.add_argument('--output', '-o', type=str, default=None)
args = parser.parse_args()

df = []
rows = []
cols = []
label = []
nplots = len(args.csv_files)
delay_threshold = 200
color = ['red', 'blue', 'orange', 'green']

nnames = 0
if args.names:
    nnames=len(args.names)
    if (nnames != nplots):
        raise Exception("Name list must have as many labels as plots")

for i, csvFile in enumerate(args.csv_files):
    _df = pd.read_csv(csvFile, sep=',', header=0)
    df.append(_df)
    rows.append(len(_df.index))
    cols.append(len(_df.columns))

    fname=None
    if args.names:
        fname=args.names[i]
    else:
        fname=os.path.splitext(os.path.basename(csvFile))[0]
    label.append(fname)

fig, axs = plt.subplots(1, 1, figsize=(8,4), layout='constrained')

data_delay = [[] for i in range(nplots)]
for j, f in enumerate(df):
    data_delay[j] = {'x':[], 'y':[]}
    for i in range(int(rows[j]/10)):
       ifirst = i * 10
       ilast  = ifirst + 10 - 1
       tmp = f.iloc[ifirst:ilast, 1]
       avg = tmp.mean()
       data_delay[j]['x'].append(f.iloc[ifirst,0])
       data_delay[j]['y'].append(avg)

ax = axs
ax.set_xlabel('Packet Injection Rate (PIR)')
ax.set_ylabel('Latency (Cycles)')
ax.set_ylim(top=delay_threshold)
ax.yaxis.set_label_coords(-0.15, 0.38)
#ax.set_title('Average Delay versus PIR')

for j, f in enumerate(df):
    ax.plot(data_delay[j]['x'], data_delay[j]['y'], 'o-',
            label=label[j], color=color[j])
ax.legend()

plt.legend(loc='upper left')
plt.grid()

if args.output:
    plt.savefig(args.output, dpi=2000)
else:
    plt.show()

