#!/usr/bin/env python3
# 
# (C) 2025 Inria, Universite Grenoble Alpes
# For the license applied to these sources refer to file ../doc/LICENSE.txt
# 
# This file allows to plot CSV files generated by the noxim_explorer tool
#
# Author: Cesar Fuguet <cesar.fuguet@univ-grenoble-alpes.fr>
# Date: February 17, 2025
#
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import argparse
import os

mpl.rcParams['axes.titleweight'] = 'bold'
mpl.rcParams['axes.titlesize'] = 'Large'
mpl.rcParams['axes.labelsize'] = 'Large'
mpl.rcParams['legend.fontsize'] = 'Large'
#plt.style.use('ggplot')

parser = argparse.ArgumentParser('Plot network explorer performance')
parser.add_argument('csv_files', nargs='+', type=str)
parser.add_argument('--names', '-n', nargs='+', type=str)
parser.add_argument('--output', '-o', type=str, default=None)
args = parser.parse_args()

df = []
rows = []
cols = []
label = []
nplots = len(args.csv_files)
delay_threshold = 300

nnames = 0
if args.names:
    nnames=len(args.names)
    if (nnames != nplots):
        raise Exception("Name list must have as many labels as plots")

for i, csvFile in enumerate(args.csv_files):
    _df = pd.read_csv(csvFile, sep=',', header=0)
    df.append(_df)
    rows.append(len(_df.index))
    cols.append(len(_df.columns))

    fname=None
    if args.names:
        fname=args.names[i]
    else:
        fname=os.path.splitext(os.path.basename(csvFile))[0]
    label.append(fname)

fig, axs = plt.subplots(2, 2, figsize=(10,5), layout='constrained')

data_delay = [[] for i in range(nplots)]
for j, f in enumerate(df):
    data_delay[j] = {'x':[], 'y':[]}
    for i in range(int(rows[j]/10)):
       ifirst = i * 10
       ilast  = ifirst + 10 - 1
       tmp = f.iloc[ifirst:ilast, 1]
       avg = tmp.mean()
       data_delay[j]['x'].append(f.iloc[ifirst,0])
       data_delay[j]['y'].append(avg)

ax = axs[0][0]
ax.set_xlabel('Packet Injection Rate (PIR)')
ax.set_ylabel('Cycles')
ax.set_ylim(top=delay_threshold)
ax.set_title('Average Delay versus PIR')
color = ['red', 'blue', 'orange', 'green']

for j, f in enumerate(df):
    ax.plot(data_delay[j]['x'], data_delay[j]['y'], 'o-',
            label=label[j], color=color[j])
ax.legend()

data_throughput = [[] for i in range(nplots)]
for j, f in enumerate(df):
    data_throughput[j] = {'x':[], 'y':[]};
    for i in range(int(rows[j]/10)):
       ifirst = i * 10
       ilast  = ifirst + 10 - 1
       tmp = f.iloc[ifirst:ilast, 2]
       avg = tmp.mean()
       data_throughput[j]['x'].append(f.iloc[ifirst,0])
       data_throughput[j]['y'].append(avg)

ax = axs[0][1]
ax.set_xlabel('Packet Injection Rate (PIR)')
ax.set_ylabel('Flits/Cycle')
ax.set_title('Throughput versus PIR')
for j, f in enumerate(df):
    ax.plot(data_throughput[j]['x'], data_throughput[j]['y'], 'o-',
            label=label[j], color=color[j])
#ax.legend()

data_maxdelay = [[] for i in range(nplots)]
for j, f in enumerate(df):
    data_maxdelay[j] = {'x':[], 'y':[]};
    for i in range(int(rows[j]/10)):
       ifirst = i * 10
       ilast  = ifirst + 10 - 1
       tmp = f.iloc[ifirst:ilast, 3]
       avg = tmp.mean()
       data_maxdelay[j]['x'].append(f.iloc[ifirst,0])
       data_maxdelay[j]['y'].append(avg)

ax = axs[1][0]
ax.set_xlabel('Packet Injection Rate (PIR)')
ax.set_ylabel('Cycles')
#ax.set_ylim(top=delay_threshold)
ax.set_title('Maximum delay versus PIR')
for j, f in enumerate(df):
    ax.plot(data_maxdelay[j]['x'], data_maxdelay[j]['y'], 'o-',
            label=label[j], color=color[j])
#ax.legend()

data_totalenergy = [[] for i in range(nplots)]
for j, f in enumerate(df):
    data_totalenergy[j] = {'x':[], 'y':[]};
    for i in range(int(rows[j]/10)):
       ifirst = i * 10
       ilast  = ifirst + 10 - 1
       tmp = f.iloc[ifirst:ilast, 4]
       avg = tmp.mean()
       data_totalenergy[j]['x'].append(f.iloc[ifirst,0])
       data_totalenergy[j]['y'].append(avg)

ax = axs[1][1]
ax.set_xlabel('Packet Injection Rate (PIR)')
ax.set_ylabel('Energy (J)')
ax.set_title('Energy versus PIR')
for j, f in enumerate(df):
    ax.plot(data_totalenergy[j]['x'], data_totalenergy[j]['y'], 'o-',
            label=label[j], color=color[j])
#ax.legend()

if args.output:
    plt.savefig(args.output, dpi=2000)
else:
    plt.show()

